--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  vars: 
    wordpress_version: "4.0.32"
    php_version: "5.4.16"

  tasks: 
  - name: Install httpd and prerequisites
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - httpd
    - php-{{ php_version }}
    - php-mysql-{{ php_version }}
    - wget 
    notify: 
    - Start web server


  - name: Install mariadb
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - mariadb
    notify: 
    - Start DB server




  - name: Get wordpress 
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'

  - name: Extract wordpress
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    ansible.builtin.unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /var/www/html
      remote_src: true

  - name: Host Wordpress
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    shell: "cp -r /var/www/html/wordpress/* /var/www/html/"
    ignore_errors: true


  handlers:
  - name: Start web server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    systemd: 
      name: httpd 
      state: restarted
      enabled: true

  - name: Start DB server
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    systemd: 
      name: mariadb 
      state: restarted
      enabled: true